spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/10PinesLabs/demo-cloud-config-properties
          ignoreLocalSshSettings: true
          hostKeyAlgorithm: ssh-rsa